import { Skill } from '../types';

export const DEFAULT_SKILLS: Skill[] = [
  // CAREER PATHS (30 Programs)
  {
    id: 'frontend-path',
    title: 'Frontend Developer',
    slug: 'frontend-developer-path',
    description: 'Master the art of building beautiful, responsive, and interactive user interfaces using modern web technologies.',
    icon: 'Layout',
    category: 'career-path',
    difficultyRange: 'Beginner to Expert',
    estimatedCompletionTime: '6 months',
    estimatedWeeks: 24,
    estimatedMonths: 6,
    careerOutcome: 'Frontend Developer',
    toolsCovered: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Testing'],
    careerOutcomes: ['Senior Frontend Developer', 'UI Architect', 'Frontend Engineer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'backend-path',
    title: 'Backend Developer',
    slug: 'backend-developer-path',
    description: 'Build scalable, secure, and high-performance server-side applications and APIs that power the modern web.',
    icon: 'Database',
    category: 'career-path',
    difficultyRange: 'Intermediate to Expert',
    estimatedCompletionTime: '6 months',
    estimatedWeeks: 24,
    estimatedMonths: 6,
    careerOutcome: 'Backend Developer',
    toolsCovered: ['Node.js', 'PostgreSQL', 'Microservices', 'System Design', 'Redis'],
    careerOutcomes: ['Backend Architect', 'Lead Engineer', 'Systems Engineer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'fullstack-path',
    title: 'Full Stack Developer',
    slug: 'full-stack-developer-path',
    description: 'Become a versatile developer capable of handling both frontend and backend development to build complete applications.',
    icon: 'Code',
    category: 'career-path',
    difficultyRange: 'Beginner to Expert',
    estimatedCompletionTime: '8 months',
    estimatedWeeks: 32,
    estimatedMonths: 8,
    careerOutcome: 'Full Stack Developer',
    toolsCovered: ['React', 'Node.js', 'MongoDB', 'TypeScript', 'AWS'],
    careerOutcomes: ['Full Stack Developer', 'Software Engineer', 'CTO'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'mobile-path',
    title: 'Mobile App Developer',
    slug: 'mobile-app-developer-path',
    description: 'Create high-quality mobile applications for iOS and Android using cross-platform and native frameworks.',
    icon: 'Smartphone',
    category: 'career-path',
    difficultyRange: 'Intermediate to Expert',
    estimatedCompletionTime: '6 months',
    estimatedWeeks: 24,
    estimatedMonths: 6,
    careerOutcome: 'Mobile App Developer',
    toolsCovered: ['React Native', 'Flutter', 'Swift', 'Kotlin', 'Firebase'],
    careerOutcomes: ['Mobile Developer', 'iOS Developer', 'Android Developer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'ui-ux-path',
    title: 'UI/UX Designer',
    slug: 'ui-ux-design-path',
    description: 'Learn the principles of user interface and user experience design to create intuitive and engaging digital products.',
    icon: 'Palette',
    category: 'career-path',
    difficultyRange: 'Beginner to Advanced',
    estimatedCompletionTime: '4 months',
    estimatedWeeks: 16,
    estimatedMonths: 4,
    careerOutcome: 'UI/UX Designer',
    toolsCovered: ['Figma', 'Adobe XD', 'Prototyping', 'User Research'],
    careerOutcomes: ['UI Designer', 'UX Designer', 'Product Designer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'product-design-path',
    title: 'Product Designer',
    slug: 'product-designer-path',
    description: 'Master the end-to-end process of designing digital products, from strategy and research to high-fidelity UI.',
    icon: 'Box',
    category: 'career-path',
    difficultyRange: 'Intermediate to Expert',
    estimatedCompletionTime: '5 months',
    estimatedWeeks: 20,
    estimatedMonths: 5,
    careerOutcome: 'Product Designer',
    toolsCovered: ['Product Strategy', 'Figma', 'Prototyping', 'Design Systems'],
    careerOutcomes: ['Senior Product Designer', 'Design Lead'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'devops-path',
    title: 'DevOps Engineer',
    slug: 'devops-engineer-path',
    description: 'Bridge the gap between development and operations by mastering automation, CI/CD, and infrastructure management.',
    icon: 'Zap',
    category: 'career-path',
    difficultyRange: 'Advanced to Expert',
    estimatedCompletionTime: '6 months',
    estimatedWeeks: 24,
    estimatedMonths: 6,
    careerOutcome: 'DevOps Engineer',
    toolsCovered: ['Kubernetes', 'Terraform', 'Jenkins', 'GitHub Actions', 'Docker'],
    careerOutcomes: ['DevOps Engineer', 'SRE', 'Cloud Architect'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'cloud-path',
    title: 'Cloud Engineer',
    slug: 'cloud-engineer-path',
    description: 'Master cloud infrastructure and services on platforms like AWS, Azure, and GCP to build scalable cloud-native apps.',
    icon: 'Cloud',
    category: 'career-path',
    difficultyRange: 'Intermediate to Expert',
    estimatedCompletionTime: '6 months',
    estimatedWeeks: 24,
    estimatedMonths: 6,
    careerOutcome: 'Cloud Engineer',
    toolsCovered: ['AWS', 'Azure', 'CloudFormation', 'Serverless'],
    careerOutcomes: ['Cloud Architect', 'Cloud Solutions Engineer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'data-analyst-path',
    title: 'Data Analyst',
    slug: 'data-analyst-path',
    description: 'Learn to collect, process, and perform statistical analyses of data to provide actionable insights for businesses.',
    icon: 'BarChart',
    category: 'career-path',
    difficultyRange: 'Beginner to Intermediate',
    estimatedCompletionTime: '4 months',
    estimatedWeeks: 16,
    estimatedMonths: 4,
    careerOutcome: 'Data Analyst',
    toolsCovered: ['SQL', 'Excel', 'Tableau', 'Python', 'PowerBI'],
    careerOutcomes: ['Business Analyst', 'Data Insights Specialist'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'data-scientist-path',
    title: 'Data Scientist',
    slug: 'data-scientist-path',
    description: 'Master the art of extracting knowledge and insights from structured and unstructured data using scientific methods.',
    icon: 'Brain',
    category: 'career-path',
    difficultyRange: 'Intermediate to Expert',
    estimatedCompletionTime: '7 months',
    estimatedWeeks: 28,
    estimatedMonths: 7,
    careerOutcome: 'Data Scientist',
    toolsCovered: ['Python', 'R', 'Statistics', 'Machine Learning', 'Pandas'],
    careerOutcomes: ['Senior Data Scientist', 'AI Researcher'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'ml-engineer-path',
    title: 'Machine Learning Engineer',
    slug: 'ml-engineer-path',
    description: 'Design and implement machine learning models and systems that can learn and make predictions from data.',
    icon: 'Cpu',
    category: 'career-path',
    difficultyRange: 'Advanced to Expert',
    estimatedCompletionTime: '7 months',
    estimatedWeeks: 28,
    estimatedMonths: 7,
    careerOutcome: 'Machine Learning Engineer',
    toolsCovered: ['TensorFlow', 'PyTorch', 'Scikit-Learn', 'Deep Learning'],
    careerOutcomes: ['ML Architect', 'AI Engineer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'ai-engineer-path',
    title: 'AI Engineer',
    slug: 'ai-engineer-path',
    description: 'Build intelligent applications using Large Language Models, Generative AI, and advanced neural networks.',
    icon: 'Sparkles',
    category: 'career-path',
    difficultyRange: 'Intermediate to Expert',
    estimatedCompletionTime: '6 months',
    estimatedWeeks: 24,
    estimatedMonths: 6,
    careerOutcome: 'AI Engineer',
    toolsCovered: ['OpenAI API', 'LangChain', 'Vector Databases', 'Prompt Engineering'],
    careerOutcomes: ['AI Solutions Architect', 'Generative AI Developer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'cybersecurity-path',
    title: 'Cybersecurity Analyst',
    slug: 'cybersecurity-analyst-path',
    description: 'Protect networks, systems, and data from digital attacks. Learn ethical hacking, defense, and risk management.',
    icon: 'Shield',
    category: 'career-path',
    difficultyRange: 'Intermediate to Expert',
    estimatedCompletionTime: '6 months',
    estimatedWeeks: 24,
    estimatedMonths: 6,
    careerOutcome: 'Cybersecurity Analyst',
    toolsCovered: ['Networking', 'Security+', 'Penetration Testing', 'SIEM'],
    careerOutcomes: ['Security Engineer', 'Ethical Hacker'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'blockchain-path',
    title: 'Blockchain Developer',
    slug: 'blockchain-developer-path',
    description: 'Master decentralized technology. Build smart contracts, DApps, and understand Web3 protocols.',
    icon: 'Link',
    category: 'career-path',
    difficultyRange: 'Advanced to Expert',
    estimatedCompletionTime: '5 months',
    estimatedWeeks: 20,
    estimatedMonths: 5,
    careerOutcome: 'Blockchain Developer',
    toolsCovered: ['Solidity', 'Ethereum', 'Web3.js', 'Smart Contracts'],
    careerOutcomes: ['Web3 Developer', 'Smart Contract Auditor'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'game-dev-path',
    title: 'Game Developer',
    slug: 'game-developer-path',
    description: 'Create immersive 2D and 3D games for desktop, mobile, and consoles using industry-standard game engines.',
    icon: 'Gamepad2',
    category: 'career-path',
    difficultyRange: 'Intermediate to Expert',
    estimatedCompletionTime: '8 months',
    estimatedWeeks: 32,
    estimatedMonths: 8,
    careerOutcome: 'Game Developer',
    toolsCovered: ['Unity', 'Unreal Engine', 'C#', 'C++', '3D Modeling'],
    careerOutcomes: ['Game Programmer', 'Technical Artist'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'qa-engineer-path',
    title: 'QA Engineer',
    slug: 'qa-engineer-path',
    description: 'Ensure software quality through manual and automated testing. Learn to build robust testing frameworks.',
    icon: 'CheckSquare',
    category: 'career-path',
    difficultyRange: 'Beginner to Intermediate',
    estimatedCompletionTime: '4 months',
    estimatedWeeks: 16,
    estimatedMonths: 4,
    careerOutcome: 'QA Engineer',
    toolsCovered: ['Selenium', 'Cypress', 'Jest', 'Test Automation'],
    careerOutcomes: ['Automation Engineer', 'SDET'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'python-dev-path',
    title: 'Python Developer',
    slug: 'python-developer-path',
    description: 'Become a professional Python developer. Focus on web development, automation, and data processing.',
    icon: 'Terminal',
    category: 'career-path',
    difficultyRange: 'Beginner to Expert',
    estimatedCompletionTime: '5 months',
    estimatedWeeks: 20,
    estimatedMonths: 5,
    careerOutcome: 'Python Developer',
    toolsCovered: ['Django', 'Flask', 'FastAPI', 'PostgreSQL'],
    careerOutcomes: ['Python Engineer', 'Backend Developer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'js-dev-path',
    title: 'JavaScript Developer',
    slug: 'javascript-developer-path',
    description: 'Master the language of the web. Deep dive into advanced JavaScript, asynchronous patterns, and modern frameworks.',
    icon: 'Code',
    category: 'career-path',
    difficultyRange: 'Beginner to Expert',
    estimatedCompletionTime: '5 months',
    estimatedWeeks: 20,
    estimatedMonths: 5,
    careerOutcome: 'JavaScript Developer',
    toolsCovered: ['Advanced JS', 'Node.js', 'TypeScript', 'React'],
    careerOutcomes: ['JS Engineer', 'Frontend Architect'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'react-dev-path',
    title: 'React Developer',
    slug: 'react-developer-path',
    description: 'Master the most popular frontend library. Learn hooks, state management, and building complex SPAs.',
    icon: 'Atom',
    category: 'career-path',
    difficultyRange: 'Intermediate to Expert',
    estimatedCompletionTime: '4 months',
    estimatedWeeks: 16,
    estimatedMonths: 4,
    careerOutcome: 'React Developer',
    toolsCovered: ['React', 'Redux', 'React Query', 'Next.js'],
    careerOutcomes: ['Senior React Developer', 'Frontend Lead'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'node-dev-path',
    title: 'Node.js Developer',
    slug: 'node-developer-path',
    description: 'Build high-performance, scalable server-side applications using Node.js and its vast ecosystem.',
    icon: 'Server',
    category: 'career-path',
    difficultyRange: 'Intermediate to Expert',
    estimatedCompletionTime: '4 months',
    estimatedWeeks: 16,
    estimatedMonths: 4,
    careerOutcome: 'Node.js Developer',
    toolsCovered: ['Node.js', 'Express', 'NestJS', 'MongoDB'],
    careerOutcomes: ['Backend Developer', 'Node.js Engineer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'java-dev-path',
    title: 'Java Developer',
    slug: 'java-developer-path',
    description: 'Master enterprise software development with Java. Learn Spring Boot, microservices, and design patterns.',
    icon: 'Coffee',
    category: 'career-path',
    difficultyRange: 'Beginner to Expert',
    estimatedCompletionTime: '7 months',
    estimatedWeeks: 28,
    estimatedMonths: 7,
    careerOutcome: 'Java Developer',
    toolsCovered: ['Java', 'Spring Boot', 'Hibernate', 'Maven'],
    careerOutcomes: ['Java Engineer', 'Enterprise Architect'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'cpp-dev-path',
    title: 'C++ Developer',
    slug: 'cpp-developer-path',
    description: 'Master high-performance systems programming with C++. Learn memory management, STL, and low-level optimization.',
    icon: 'Terminal',
    category: 'career-path',
    difficultyRange: 'Intermediate to Expert',
    estimatedCompletionTime: '7 months',
    estimatedWeeks: 28,
    estimatedMonths: 7,
    careerOutcome: 'C++ Developer',
    toolsCovered: ['C++', 'STL', 'Multi-threading', 'Memory Management'],
    careerOutcomes: ['Systems Programmer', 'Game Engine Developer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'php-dev-path',
    title: 'PHP Developer',
    slug: 'php-developer-path',
    description: 'Master modern PHP development. Learn Laravel, Symfony, and building robust web applications.',
    icon: 'Globe',
    category: 'career-path',
    difficultyRange: 'Beginner to Expert',
    estimatedCompletionTime: '5 months',
    estimatedWeeks: 20,
    estimatedMonths: 5,
    careerOutcome: 'PHP Developer',
    toolsCovered: ['PHP', 'Laravel', 'MySQL', 'Composer'],
    careerOutcomes: ['PHP Engineer', 'Web Developer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'wordpress-dev-path',
    title: 'WordPress Developer',
    slug: 'wordpress-developer-path',
    description: 'Learn to build custom themes, plugins, and headless WordPress solutions for professional clients.',
    icon: 'Layout',
    category: 'career-path',
    difficultyRange: 'Beginner to Intermediate',
    estimatedCompletionTime: '4 months',
    estimatedWeeks: 16,
    estimatedMonths: 4,
    careerOutcome: 'WordPress Developer',
    toolsCovered: ['PHP', 'Theme Development', 'Plugin Development', 'Headless WP'],
    careerOutcomes: ['WP Developer', 'Freelance Web Developer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'api-dev-path',
    title: 'API Developer',
    slug: 'api-developer-path',
    description: 'Master the design and implementation of robust, secure, and well-documented APIs using REST and GraphQL.',
    icon: 'ArrowRightLeft',
    category: 'career-path',
    difficultyRange: 'Intermediate to Expert',
    estimatedCompletionTime: '4 months',
    estimatedWeeks: 16,
    estimatedMonths: 4,
    careerOutcome: 'API Developer',
    toolsCovered: ['REST', 'GraphQL', 'gRPC', 'API Security'],
    careerOutcomes: ['API Engineer', 'Integration Specialist'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'database-dev-path',
    title: 'Database Developer',
    slug: 'database-developer-path',
    description: 'Master database design, optimization, and management across SQL and NoSQL systems.',
    icon: 'Database',
    category: 'career-path',
    difficultyRange: 'Intermediate to Expert',
    estimatedCompletionTime: '5 months',
    estimatedWeeks: 20,
    estimatedMonths: 5,
    careerOutcome: 'Database Developer',
    toolsCovered: ['PostgreSQL', 'MongoDB', 'Query Optimization', 'DBA'],
    careerOutcomes: ['DBA', 'Data Engineer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'software-engineer-path',
    title: 'Software Engineer',
    slug: 'software-engineer-path',
    description: 'Master the fundamentals of software engineering, including algorithms, data structures, and system design.',
    icon: 'Code',
    category: 'career-path',
    difficultyRange: 'Beginner to Expert',
    estimatedCompletionTime: '9 months',
    estimatedWeeks: 36,
    estimatedMonths: 9,
    careerOutcome: 'Software Engineer',
    toolsCovered: ['Computer Science', 'System Design', 'Algorithms', 'Testing'],
    careerOutcomes: ['Software Engineer', 'Technical Lead'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'systems-engineer-path',
    title: 'Systems Engineer',
    slug: 'systems-engineer-path',
    description: 'Learn to design and manage complex systems, focusing on reliability, scalability, and performance.',
    icon: 'Settings',
    category: 'career-path',
    difficultyRange: 'Advanced to Expert',
    estimatedCompletionTime: '8 months',
    estimatedWeeks: 32,
    estimatedMonths: 8,
    careerOutcome: 'Systems Engineer',
    toolsCovered: ['Linux', 'Networking', 'Distributed Systems', 'Security'],
    careerOutcomes: ['Systems Architect', 'Infrastructure Lead'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'automation-engineer-path',
    title: 'Automation Engineer',
    slug: 'automation-engineer-path',
    description: 'Learn to automate repetitive tasks and workflows using scripting and specialized automation tools.',
    icon: 'Zap',
    category: 'career-path',
    difficultyRange: 'Intermediate to Expert',
    estimatedCompletionTime: '5 months',
    estimatedWeeks: 20,
    estimatedMonths: 5,
    careerOutcome: 'Automation Engineer',
    toolsCovered: ['Python', 'Bash', 'Ansible', 'Puppet'],
    careerOutcomes: ['Automation Architect', 'DevOps Engineer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'tech-support-path',
    title: 'Technical Support Engineer',
    slug: 'technical-support-engineer-path',
    description: 'Learn to troubleshoot and resolve technical issues for software and hardware products.',
    icon: 'Headphones',
    category: 'career-path',
    difficultyRange: 'Beginner to Intermediate',
    estimatedCompletionTime: '3 months',
    estimatedWeeks: 12,
    estimatedMonths: 3,
    careerOutcome: 'Technical Support Engineer',
    toolsCovered: ['Troubleshooting', 'Customer Service', 'Linux', 'Networking'],
    careerOutcomes: ['Support Lead', 'Customer Success Engineer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },

  // DEVELOPMENT SKILLS
  {
    id: 'frontend-skill',
    title: 'Frontend Development',
    slug: 'frontend-development-skill',
    description: 'Master the art of building beautiful, responsive, and interactive user interfaces using modern web technologies.',
    icon: 'Layout',
    category: 'development-skill',
    difficultyRange: 'Beginner to Expert',
    estimatedCompletionTime: '6 months',
    estimatedWeeks: 24,
    estimatedMonths: 6,
    careerOutcome: 'Frontend Developer',
    toolsCovered: ['HTML5', 'CSS3', 'JavaScript', 'React', 'Tailwind CSS'],
    careerOutcomes: ['Frontend Developer', 'Web Developer', 'UI Engineer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'backend-skill',
    title: 'Backend Development',
    slug: 'backend-development-skill',
    description: 'Build scalable, secure, and high-performance server-side applications and APIs that power the modern web.',
    icon: 'Database',
    category: 'development-skill',
    difficultyRange: 'Intermediate to Expert',
    estimatedCompletionTime: '6 months',
    estimatedWeeks: 24,
    estimatedMonths: 6,
    careerOutcome: 'Backend Developer',
    toolsCovered: ['Node.js', 'Express', 'PostgreSQL', 'Redis', 'Docker'],
    careerOutcomes: ['Backend Developer', 'Systems Engineer', 'API Developer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'fullstack-skill',
    title: 'Full Stack Development',
    slug: 'full-stack-development-skill',
    description: 'Become a versatile developer capable of handling both frontend and backend development to build complete applications.',
    icon: 'Code',
    category: 'development-skill',
    difficultyRange: 'Beginner to Expert',
    estimatedCompletionTime: '8 months',
    estimatedWeeks: 32,
    estimatedMonths: 8,
    careerOutcome: 'Full Stack Developer',
    toolsCovered: ['React', 'Node.js', 'MongoDB', 'TypeScript', 'AWS'],
    careerOutcomes: ['Full Stack Developer', 'Software Engineer', 'CTO'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'mobile-skill',
    title: 'Mobile App Development',
    slug: 'mobile-app-development-skill',
    description: 'Create high-quality mobile applications for iOS and Android using cross-platform and native frameworks.',
    icon: 'Smartphone',
    category: 'development-skill',
    difficultyRange: 'Intermediate to Expert',
    estimatedCompletionTime: '6 months',
    estimatedWeeks: 24,
    estimatedMonths: 6,
    careerOutcome: 'Mobile App Developer',
    toolsCovered: ['React Native', 'Flutter', 'Swift', 'Kotlin', 'Firebase'],
    careerOutcomes: ['Mobile Developer', 'iOS Developer', 'Android Developer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'ui-ux-skill',
    title: 'UI/UX Design',
    slug: 'ui-ux-design-skill',
    description: 'Learn the principles of user interface and user experience design to create intuitive and engaging digital products.',
    icon: 'Palette',
    category: 'development-skill',
    difficultyRange: 'Beginner to Advanced',
    estimatedCompletionTime: '4 months',
    estimatedWeeks: 16,
    estimatedMonths: 4,
    careerOutcome: 'UI/UX Designer',
    toolsCovered: ['Figma', 'Adobe XD', 'Prototyping', 'User Research'],
    careerOutcomes: ['UI Designer', 'UX Designer', 'Product Designer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'devops-skill',
    title: 'DevOps',
    slug: 'devops-skill',
    description: 'Bridge the gap between development and operations by mastering automation, CI/CD, and infrastructure management.',
    icon: 'Zap',
    category: 'development-skill',
    difficultyRange: 'Advanced to Expert',
    estimatedCompletionTime: '6 months',
    estimatedWeeks: 24,
    estimatedMonths: 6,
    careerOutcome: 'DevOps Engineer',
    toolsCovered: ['Kubernetes', 'Terraform', 'Jenkins', 'GitHub Actions', 'Docker'],
    careerOutcomes: ['DevOps Engineer', 'SRE', 'Cloud Architect'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },

  // CODING LANGUAGES
  {
    id: 'html-lang',
    title: 'HTML Mastery',
    slug: 'html-mastery-lang',
    description: 'Master the backbone of the web. Learn semantic HTML, accessibility, and modern web standards.',
    icon: 'Layout',
    category: 'coding-languages',
    difficultyRange: 'Beginner',
    estimatedCompletionTime: '1 month',
    estimatedWeeks: 4,
    estimatedMonths: 1,
    careerOutcome: 'Web Developer',
    toolsCovered: ['HTML5', 'Semantic Web', 'Accessibility', 'SEO'],
    careerOutcomes: ['Web Developer', 'Frontend Developer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'css-lang',
    title: 'CSS Mastery',
    slug: 'css-mastery-lang',
    description: 'Master the art of styling the web. From CSS basics to advanced layouts with Flexbox, Grid, and animations.',
    icon: 'Palette',
    category: 'coding-languages',
    difficultyRange: 'Beginner to Advanced',
    estimatedCompletionTime: '2 months',
    estimatedWeeks: 8,
    estimatedMonths: 2,
    careerOutcome: 'CSS Specialist',
    toolsCovered: ['CSS3', 'Flexbox', 'CSS Grid', 'Animations', 'Responsive Design'],
    careerOutcomes: ['Frontend Developer', 'UI Developer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'js-lang',
    title: 'JavaScript Programming',
    slug: 'javascript-programming-lang',
    description: 'Master JavaScript from zero to professional level. Learn core syntax, DOM manipulation, and modern ES6+ features.',
    icon: 'Code',
    category: 'coding-languages',
    difficultyRange: 'Beginner to Advanced',
    estimatedCompletionTime: '4.5 months',
    estimatedWeeks: 18,
    estimatedMonths: 4.5,
    careerOutcome: 'JavaScript Specialist',
    toolsCovered: ['JavaScript', 'ES6+', 'Web APIs', 'Node.js'],
    careerOutcomes: ['Frontend Developer', 'Full Stack Developer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'ts-lang',
    title: 'TypeScript Programming',
    slug: 'typescript-programming-lang',
    description: 'Learn TypeScript to build scalable and maintainable applications with static typing.',
    icon: 'Code2',
    category: 'coding-languages',
    difficultyRange: 'Intermediate',
    estimatedCompletionTime: '2 months',
    estimatedWeeks: 8,
    estimatedMonths: 2,
    careerOutcome: 'TypeScript Developer',
    toolsCovered: ['TypeScript', 'Static Typing', 'Interfaces', 'Generics'],
    careerOutcomes: ['Frontend Engineer', 'Full Stack Engineer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'python-lang',
    title: 'Python Programming',
    slug: 'python-programming-lang',
    description: 'Learn Python, the most versatile programming language. From basic syntax to advanced OOP and automation.',
    icon: 'Terminal',
    category: 'coding-languages',
    difficultyRange: 'Beginner to Advanced',
    estimatedCompletionTime: '4.5 months',
    estimatedWeeks: 18,
    estimatedMonths: 4.5,
    careerOutcome: 'Python Specialist',
    toolsCovered: ['Python', 'Data Structures', 'Algorithms', 'Automation'],
    careerOutcomes: ['Python Developer', 'Data Scientist'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'java-lang',
    title: 'Java Programming',
    slug: 'java-programming-lang',
    description: 'Master Java, the backbone of enterprise applications. Learn core Java, OOP, and multithreading.',
    icon: 'Coffee',
    category: 'coding-languages',
    difficultyRange: 'Beginner to Advanced',
    estimatedCompletionTime: '5 months',
    estimatedWeeks: 20,
    estimatedMonths: 5,
    careerOutcome: 'Java Developer',
    toolsCovered: ['Java', 'OOP', 'Spring Boot', 'Multithreading'],
    careerOutcomes: ['Enterprise Developer', 'Android Developer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'c-lang',
    title: 'C Programming',
    slug: 'c-programming-lang',
    description: 'Learn the fundamentals of computer science with C. Understand memory management and low-level programming.',
    icon: 'Cpu',
    category: 'coding-languages',
    difficultyRange: 'Beginner to Advanced',
    estimatedCompletionTime: '4 months',
    estimatedWeeks: 16,
    estimatedMonths: 4,
    careerOutcome: 'Systems Programmer',
    toolsCovered: ['C', 'Memory Management', 'Pointers', 'Data Structures'],
    careerOutcomes: ['Embedded Systems Engineer', 'Systems Programmer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'cpp-lang',
    title: 'C++ Programming',
    slug: 'cpp-programming-lang',
    description: 'Master C++ for high-performance applications, game development, and systems programming.',
    icon: 'Zap',
    category: 'coding-languages',
    difficultyRange: 'Intermediate to Advanced',
    estimatedCompletionTime: '5 months',
    estimatedWeeks: 20,
    estimatedMonths: 5,
    careerOutcome: 'C++ Developer',
    toolsCovered: ['C++', 'STL', 'Memory Management', 'Game Dev'],
    careerOutcomes: ['Game Developer', 'Systems Engineer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'csharp-lang',
    title: 'C# Programming',
    slug: 'csharp-programming-lang',
    description: 'Learn C# for building Windows applications, web services with .NET, and games with Unity.',
    icon: 'Hash',
    category: 'coding-languages',
    difficultyRange: 'Beginner to Advanced',
    estimatedCompletionTime: '4 months',
    estimatedWeeks: 16,
    estimatedMonths: 4,
    careerOutcome: 'C# Developer',
    toolsCovered: ['C#', '.NET', 'Unity', 'ASP.NET'],
    careerOutcomes: ['Game Developer', 'Enterprise Developer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'php-lang',
    title: 'PHP Programming',
    slug: 'php-programming-lang',
    description: 'Master PHP, the language that powers over 75% of the web. Learn modern PHP and Laravel.',
    icon: 'Globe',
    category: 'coding-languages',
    difficultyRange: 'Beginner to Advanced',
    estimatedCompletionTime: '4 months',
    estimatedWeeks: 16,
    estimatedMonths: 4,
    careerOutcome: 'PHP Developer',
    toolsCovered: ['PHP', 'Laravel', 'MySQL', 'Composer'],
    careerOutcomes: ['Web Developer', 'Backend Developer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'go-lang',
    title: 'Go Programming',
    slug: 'go-programming-lang',
    description: 'Learn Go (Golang), the language designed for cloud-native development and high-performance services.',
    icon: 'Cloud',
    category: 'coding-languages',
    difficultyRange: 'Intermediate',
    estimatedCompletionTime: '3 months',
    estimatedWeeks: 12,
    estimatedMonths: 3,
    careerOutcome: 'Go Developer',
    toolsCovered: ['Go', 'Concurrency', 'Microservices', 'Docker'],
    careerOutcomes: ['Cloud Engineer', 'Backend Developer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'rust-lang',
    title: 'Rust Programming',
    slug: 'rust-programming-lang',
    description: 'Master Rust for safe, fast, and concurrent systems programming. Learn the borrow checker and ownership.',
    icon: 'Shield',
    category: 'coding-languages',
    difficultyRange: 'Advanced',
    estimatedCompletionTime: '5 months',
    estimatedWeeks: 20,
    estimatedMonths: 5,
    careerOutcome: 'Rust Developer',
    toolsCovered: ['Rust', 'Memory Safety', 'Concurrency', 'WebAssembly'],
    careerOutcomes: ['Systems Engineer', 'Blockchain Developer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'swift-lang',
    title: 'Swift Programming',
    slug: 'swift-programming-lang',
    description: 'Learn Swift to build beautiful and powerful applications for iOS, macOS, and beyond.',
    icon: 'Smartphone',
    category: 'coding-languages',
    difficultyRange: 'Beginner to Advanced',
    estimatedCompletionTime: '4 months',
    estimatedWeeks: 16,
    estimatedMonths: 4,
    careerOutcome: 'iOS Developer',
    toolsCovered: ['Swift', 'SwiftUI', 'iOS SDK', 'Xcode'],
    careerOutcomes: ['iOS Developer', 'Apple Platform Developer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'kotlin-lang',
    title: 'Kotlin Programming',
    slug: 'kotlin-programming-lang',
    description: 'Master Kotlin for modern Android development and server-side applications.',
    icon: 'Smartphone',
    category: 'coding-languages',
    difficultyRange: 'Beginner to Advanced',
    estimatedCompletionTime: '4 months',
    estimatedWeeks: 16,
    estimatedMonths: 4,
    careerOutcome: 'Android Developer',
    toolsCovered: ['Kotlin', 'Android SDK', 'Coroutines', 'Jetpack Compose'],
    careerOutcomes: ['Android Developer', 'Full Stack Developer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'dart-lang',
    title: 'Dart Programming',
    slug: 'dart-programming-lang',
    description: 'Learn Dart, the language behind Flutter, to build high-performance cross-platform apps.',
    icon: 'Layers',
    category: 'coding-languages',
    difficultyRange: 'Beginner to Advanced',
    estimatedCompletionTime: '3 months',
    estimatedWeeks: 12,
    estimatedMonths: 3,
    careerOutcome: 'Flutter Developer',
    toolsCovered: ['Dart', 'Flutter', 'Async Programming'],
    careerOutcomes: ['Mobile Developer', 'Frontend Developer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'ruby-lang',
    title: 'Ruby Programming',
    slug: 'ruby-programming-lang',
    description: 'Learn Ruby and the Rails framework to build web applications with speed and elegance.',
    icon: 'Gem',
    category: 'coding-languages',
    difficultyRange: 'Beginner to Advanced',
    estimatedCompletionTime: '4 months',
    estimatedWeeks: 16,
    estimatedMonths: 4,
    careerOutcome: 'Ruby on Rails Developer',
    toolsCovered: ['Ruby', 'Ruby on Rails', 'Testing', 'PostgreSQL'],
    careerOutcomes: ['Web Developer', 'Backend Developer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'r-lang',
    title: 'R Programming',
    slug: 'r-programming-lang',
    description: 'Master R for statistical computing, data analysis, and visualization.',
    icon: 'BarChart',
    category: 'coding-languages',
    difficultyRange: 'Intermediate',
    estimatedCompletionTime: '4 months',
    estimatedWeeks: 16,
    estimatedMonths: 4,
    careerOutcome: 'Data Analyst',
    toolsCovered: ['R', 'Tidyverse', 'ggplot2', 'Statistics'],
    careerOutcomes: ['Data Scientist', 'Statistical Programmer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'sql-lang',
    title: 'SQL Mastery',
    slug: 'sql-mastery-lang',
    description: 'Master SQL to manage and query databases effectively. Learn everything from basic SELECTs to complex joins and optimization.',
    icon: 'Database',
    category: 'coding-languages',
    difficultyRange: 'Beginner to Advanced',
    estimatedCompletionTime: '2 months',
    estimatedWeeks: 8,
    estimatedMonths: 2,
    careerOutcome: 'Database Specialist',
    toolsCovered: ['SQL', 'PostgreSQL', 'MySQL', 'Database Design'],
    careerOutcomes: ['Data Analyst', 'Backend Developer', 'Database Administrator'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },

  // TOOLS & FOUNDATIONS
  {
    id: 'git-foundation',
    title: 'Git and GitHub',
    slug: 'git-and-github-foundation',
    description: 'Master version control and collaborative development using Git and GitHub, essential for every developer.',
    icon: 'Github',
    category: 'tool-foundation',
    difficultyRange: 'Beginner to Intermediate',
    estimatedCompletionTime: '1 month',
    estimatedWeeks: 4,
    estimatedMonths: 1,
    careerOutcome: 'Software Engineer',
    toolsCovered: ['Git', 'GitHub', 'Workflows', 'Branching'],
    careerOutcomes: ['Software Engineer', 'Open Source Contributor'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'api-foundation',
    title: 'API Development',
    slug: 'api-development-foundation',
    description: 'Master the design and implementation of robust, secure, and well-documented APIs using REST and GraphQL.',
    icon: 'ArrowRightLeft',
    category: 'tool-foundation',
    difficultyRange: 'Intermediate to Expert',
    estimatedCompletionTime: '3 months',
    estimatedWeeks: 12,
    estimatedMonths: 3,
    careerOutcome: 'API Engineer',
    toolsCovered: ['REST', 'GraphQL', 'Postman', 'OAuth'],
    careerOutcomes: ['API Developer', 'Integration Engineer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },

  // CAREER PREP
  {
    id: 'portfolio-prep',
    title: 'Portfolio Building',
    slug: 'portfolio-building-prep',
    description: 'Learn to showcase your work effectively and build a professional portfolio that stands out to recruiters.',
    icon: 'Rocket',
    category: 'career-prep',
    difficultyRange: 'Beginner to Expert',
    estimatedCompletionTime: '1 month',
    estimatedWeeks: 4,
    estimatedMonths: 1,
    careerOutcome: 'Job-Ready Developer',
    toolsCovered: ['Portfolio Design', 'Case Studies', 'Personal Branding'],
    careerOutcomes: ['Job-Ready Developer', 'Freelancer'],
    certificateEligible: true,
    published: true,
    status: 'active'
  },
  {
    id: 'interview-prep',
    title: 'Technical Interview Prep',
    slug: 'technical-interview-prep',
    description: 'Master the technical interview process, from data structures and algorithms to system design and behavioral questions.',
    icon: 'GraduationCap',
    category: 'career-prep',
    difficultyRange: 'Intermediate to Expert',
    estimatedCompletionTime: '2 months',
    estimatedWeeks: 8,
    estimatedMonths: 2,
    careerOutcome: 'Job-Ready Developer',
    toolsCovered: ['Algorithms', 'Data Structures', 'Mock Interviews'],
    careerOutcomes: ['Software Engineer', 'Tech Consultant'],
    certificateEligible: true,
    published: true,
    status: 'active'
  }
];
